version: '3.9'
services:
  app: 
    build: .
    container_name: go
    env_file:
      - .env
    # this option keeps restarting the container until
    #it,s connectd succseefly to the database container
    restart: always
    ports:
      - 80:9090
    depends_on:
      - db
    volumes:
      - app-data:/app/data

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - db.env     
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  app-data:
  db-data: