version: '3.9'
services:
  app: 
    build: .
    container_name: go
    env_file:
      - .env
    # this option keeps restarting the container until the db is ready and healthy,
    # insted of making health check on both of them ,
    # i think it,s good for this tiny app and do the job as required 
    restart: always
    ports:
      - 80:9090
    depends_on:
      - db
    volumes:
      - app-data:/app/data
    networks:
      - netlink

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - db.env     
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - netlink

volumes:
  app-data:
  db-data:

networks:
  netlink:
