apiVersion: v1
kind: Service
metadata:
  name: instaap-service
spec:
  selector:
    app: instaap
  type: {{ .Values.app-service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app-service.port }}
      targetPort: {{ .Values.app-service.targetport }}
