apiVersion: v1
kind: Namespace
metadata:
  name: instaap
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instaap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AdamAFD/Instabug-Infrastructure-Internship-Challenge/tree/main/instaapp-helm
    path: templates
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: instaap
  syncPolicy:
    syncOptions:
    -CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
