apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  root-password: QWRhYWFhYW1tbTI1MTZmZ2RmZGc9PQ==
  user: aW5zdGFiZWc=
  password: aW5zdGFiZWdfRGV2T3Bz
  database: aW50ZXJuc2hpcA==
  port: MzMwNg==
